esphome:
  name: openbot
  includes:
#    - MyIMU.h
    - OpenBot.h
#    - gyro/Adafruit_L3GD20_U.h
#    - gyro/Adafruit_L3GD20_U.cpp
#  platformio_options:
#  libraries:
#      - FastLED@3.2.1
#      - ericksimoes/Ultrasonic
#      - 689 # arduino-libraries/Madgwick
#      - 14  # adafruit/Adafruit 9DOF Library
#      - 23  # adafruit/Adafruit L3GD20 U
#      - 6775 # Adafruit LSM303 Accel

esp8266:
  board: d1_mini_pro
  framework:
    version: recommended

custom_component:
  - id: openbot
    lambda: |-
      auto c = new OpenBot();
      return {c};

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.0.160
    gateway: 192.168.0.1
    subnet: 255.255.255.0

api:
  reboot_timeout: 0s

ota:
  - platform: esphome

logger:
  baud_rate: 0
  logs:
    sensor: INFO
    ultrasonic.sensor: INFO

web_server:

sensor:
  - platform: ultrasonic
    trigger_pin: D3
    echo_pin: D4
    id: ultrasonic_sensor
    timeout: 3m # meters
    update_interval: 200ms
    filters:
      - median:

binary_sensor:
#  - platform: gpio
#    pin:
#      inverted: True
#      number: 35
#    name: "IR Left"
#    id: "ir_left"
#  - platform: gpio
#    pin:
#      inverted: True
#      number: 0
#    name: "IR Right"
#    id: "ir_right"
