
esphome:
  name: openbot
  platform: ESP32
  board: lolin32
  includes:
    - OpenBot.h
  platformio_options:
    lib_deps:
      - ESP32 AnalogWrite
      - FastLED@3.2.1
      - ericksimoes/Ultrasonic

custom_component:
  - id: openbot
    lambda: |-
      auto c = new OpenBot();
      return {c};

wifi:
  ssid: j-link
  password: PartyKerti21
  manual_ip:
    static_ip: 192.168.0.160
    gateway: 192.168.0.1
    subnet: 255.255.255.0

api:
  reboot_timeout: 0s

ota:

logger:
  baud_rate: 0

web_server:

binary_sensor:
  - platform: gpio
    pin:
      inverted: True
      number: 35
    name: "IR Left"
    id: "ir_left"
  - platform: gpio
    pin:
      inverted: True
      number: 0
    name: "IR Right"
    id: "ir_right"

light:
#  - platform: neopixelbus
#    variant: WS2812X
  - platform: fastled_clockless
    chipset: WS2812B
    rgb_order: RBG
#    max_refresh_rate: 10ms
    pin: 19
    num_leds: 4
    name: "Lights"
    id: lights
